surogaAPI/core/urls.py
from django.urls import path, include,re_path
from rest_framework import routers, serializers, viewsets
from core.views import time_zoneViewSet , RideDurationViewSet #, ServiceTypeViewSet
#from core.views import PathTypeViewSet, LocalViewSet, CountryViewSet, CurrencyViewSet, LanguageViewSet # TechnologyViewSet,
from core.views import CountryViewSet, CurrencyViewSet, LanguageViewSet # TechnologyViewSet,
from core.views import districtregionViewSet, citymunicipalityViewSet
from core.views import equipmentViewSet, publiceventViewSet, soundViewSet, imageViewSet, localwifiViewSet 
from core.views import eventsViewSet

"""
Suroga API - Core Application URL Configuration

This module defines the URL routing for the Core application within the Suroga API project. Utilizing
Django Rest Framework's routing mechanisms, this configuration maps URL patterns to views for handling
API requests related to core functionalities such as time zones, ride durations, countries, currencies,
languages, and more.

Routes are defined using Django's path and include functions, as well as DRF routers for automatically
generating URLs for view sets. This setup is designed to be scalable and easily maintainable as the
application and its API capabilities continue to grow and evolve.

Each URL pattern corresponds to a specific view set, outlining the way HTTP requests are processed,
and determining the behavior expected for CRUD operations on the associated model instances.

References:
    - Django URL dispatcher documentation: https://docs.djangoproject.com/en/4.0/topics/http/urls/
    - Django Rest Framework routing: https://www.django-rest-framework.org/api-guide/routers/

Note: This file should only be modified if changes to URL patterns are required, ensuring that the
modifications adhere to the existing architectural standards and naming conventions.

Maintainer:  Carlos Leandro
Last Modified: 15/3/2024
"""

# Define the app namespace to allow for reverse-matching of URLs within this 'core' app.
app_name = 'core'

# Set up the Django Rest Framework (DRF) router, which helps generate URL patterns for a ViewSet automatically.
# The DRF routers determine the URL conf based on common naming conventions for common CRUD (Create-Read-Update-Delete) operations.
router = routers.DefaultRouter()

# The router registers multiple view sets with the corresponding URL pattern.
# This allows DRF to auto-generate URLs for accessing the API endpoints,
# typically ones that map closely to database models for CRUD operations.

# Each register call adds a new route to handle requests for listed time zones, durations, countries, currencies, etc. 
router.register(r'time_zones', time_zoneViewSet)
router.register(r'duration', RideDurationViewSet)
router.register(r'country', CountryViewSet)
router.register(r'currency', CurrencyViewSet)
router.register(r'language', LanguageViewSet)
router.register(r'district_region', districtregionViewSet)
router.register(r'city_municipality', citymunicipalityViewSet)
router.register(r'equipment', equipmentViewSet)
router.register(r'public_event', publiceventViewSet)
router.register(r'sound_requirements', soundViewSet)
router.register(r'image_requirements', imageViewSet)
router.register(r'local_wifi', localwifiViewSet)
router.register(r'events', eventsViewSet)


# urlpatterns is the list of URL patterns recognized by the app.
# Each element in the list associates a route pattern with a view or include for further pattern matching.
urlpatterns = [
    # Includes URL patterns for the 'rides' app within this 'core' app. The namespace 'rides' helps ensure reverse URL matching is unique.
    path('rides/',include('rides.urls', namespace='rides')),
    
    # Include router-generated URL patterns, which will cover the CRUD URLs for all registered view sets.
    # This is a shorthand to include all the URLs handled by the router, allowing DRF to handle the request dispatching.
    path('', include(router.urls)),
]

surogaAPI/partner/urls.py
"""
Partner Application URL Configuration - Suroga API

This module outlines the URL patterns for the Partner application, responsible for facilitating
web requests to appropriate views related to partner management and operations within the Suroga API.

By defining these patterns, the application can serve different web pages and API endpoints,
effectively mapping URL routes to the functions that handle requests for those routes.

Usage:
    - Include these URL patterns in the project's main `urls.py` file using Django's `include()` function.
    - Use the `name` parameter to reverse these URLs in templates and views for consistent URL referencing.

Patterns:
    - Authentication views are provided by Django's built-in auth views with additional customization.
    - Sign-up, login, profile management, and other functionalities relevant to partner management are routed here.
    - Custom views for specific partner interactions are defined with clear, actionable names.

References:
    - Django URL dispatcher: https://docs.djangoproject.com/en/4.0/topics/http/urls/
    - Django Authentication Views: https://docs.djangoproject.com/en/4.0/topics/auth/default/#module-django.contrib.auth.views

Ensure that all views are properly imported and available for creating URL patterns, and that the
named URL patterns match those used in the rest of the application for consistency.

Maintainer: Carlos Leandro
Last Modified: 15/3/2024
"""
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path as url
from django.contrib.auth import views as auth_views
from rest_framework import routers, serializers, viewsets
from rest_framework.schemas import get_schema_view

from core import views as coreviews
from partner import forms as partnerforms
from partner import views as partnerviews

app_name = 'partner'

urlpatterns = [
    # Change password view for a partner
    url(r'^password/$', partnerviews.change_password, name='password_change'),
    
    # Logout view which redirects to the home page after logging out
    url(r'^logout/$',auth_views.LogoutView.as_view(next_page = '/'), name='logout'),
    
    # Signup view for new clients
    url(r'^signup/$',partnerviews.ClientSignUp.as_view(), name='client_signup'),
    
    # Login view with a custom authentication form and a language code in the context
    url(r'^login/$', auth_views.LoginView.as_view(template_name = 'partner/clientlogin.html',
        authentication_form = partnerforms.CustomAuthenticationForm, extra_context = {'code':'en'}), name='login'),
    
    # Confirm login attempt view
    url(r'^confirmLogin/$', partnerviews.confirmLogin, name='confirmLogin'),
    
    # Profile update view for a client with a specific primary key (pk)
    path('clientProfile/<int:pk>/', partnerviews.clientProfile.as_view(), name='profile-update'),  
    
    # View for updating, adding, and deleting contacts
    path('contactUpdate/<int:pk>/',partnerviews.ContactUpdate.as_view(), name='contact-update'),
    path('contactAdd/',partnerviews.ContactsAdd.as_view(), name='contact-add'),
    path('contactDelete/<int:pk>/', partnerviews.ContactsDelete.as_view(), name='contact-delete'),
    
    # View for updating, adding, and deleting location information
    path('localUpdate/<int:pk>/',partnerviews.LocalUpdate.as_view(), name='local-update'),
    path('localAdd/',partnerviews.LocalAdd.as_view(), name='local-add'),
    path('localDelete/<int:pk>/', partnerviews.LocalDelete.as_view(), name='local-delete'),
    
    # Confirm view for account confirmation operations
    url(r'^confirm/$', partnerviews.confirm, name='confirm'),
    
    # Search and view transactions, requests, and login data within a given date range
    path('searchTransactions/<str:start>/<str:end>/', partnerviews.searchTransaction, name='searchTransaction'),
    path('searchRequests/<str:start>/<str:end>/', partnerviews.searchRequests, name='searchRequests'),
    path('searchLogin/<str:start>/<str:end>/', partnerviews.searchLogin, name='searchLogin'),
    path('viewTransation/<int:pk>/', partnerviews.viewTransation, name='viewTransation'),
    path('viewRequest/<int:pk>/', partnerviews.viewRequest, name='viewRequest'),
    path('viewLogin/<int:pk>/', partnerviews.viewLogin, name='viewLogin'),
    
    # The main dashboard view for clients
    path('',partnerviews.ClientDashboard, name='client_dashboard'),
]

surogaAPI/surogaAPI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path as url
from django.contrib.auth import views as auth_views
from rest_framework import routers, serializers, viewsets
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

from core import views as coreviews

# urlpatterns define the URL routing for the Suroga API project.
urlpatterns = [
    # Includes URL patterns from the 'partner' app, using a namespace to differentiate these URLs
    # from others that may have the same name in different apps.
    path('partner/',include('partner.urls', namespace='partner')),
    
    # Django's built-in administrative interface. Only intended for use by site administrators.
    path('admin/', admin.site.urls),
    
    # Includes URL patterns from the 'core' app, namespaced for 'core', used for API endpoints.
    path('api/v1/',include('core.urls', namespace='core')),
    
    # URLs for Django REST framework's own login and logout views.
    # These are typically used for browsable API views, which are useful during development.
    path('api-auth/', include('rest_framework.urls')),
    
    # Generates and serves the API documentation page using Django REST framework's documentation feature.
    # These URLs are serialized and presented in an interface for developers to read and understand
    # the capabilities of the API.
    path('docs', include_docs_urls(
        title="SurOO openapi: Surrogate your rides",
        description="API is used to build bridges between the real and the virtual world.\n Surrogate rides in your APP.",
    )),


    # Serves the generated OpenAPI schema at the `/openapi` endpoint, providing a machine-readable
    # definition of the API that can be used by a variety of tools, such as code generators, documentation
    # generators, and API testing tools. The OpenAPI standard is widely supported and enables interoperability.
    path('openapi', get_schema_view(
        title="SurOO openapi: Surrogate your rides",
        description="API is used to build bridges between the real and the virtual world.\n Surrogate rides in your APP.",
        version="1.0.0"
    ), name='openapi-schema'),
   
    # The root endpoint of the website, which serves the index view from the 'core' app. This view
    # might display a landing page or redirect to a main part of the application.
    path('', coreviews.index, name='index'),
]

surogaAPI/templates/partner/clientlogin.html
{% load static %}
{% load i18n %}

{% language  request.session.code  %}
<p style="padding-bottom: 1cm;"></p>
<div class="row">
    <div class="col-md-12 text-center">
        <form method="post" class="form-horizontal" action="{% url 'partner:login' %}" id="loginform"> 
            {% csrf_token %}

            {% for field in form %}
            <div class="row">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <div class="form-group">
                    {{ field }}
                    </div>
                </div>
            </div>
            {% endfor %}
            <p style="color: red">{{ form.username.errors }} </p>   
            <p style="color: red">{{ form.password.errors }} </p>  
            <div class="row">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">    
                <input type="submit" value = '{% trans "Continue" %}' class="btn btn-green btn-block">
                <input type="hidden" name="next" value="{{ next }}" >
                </div>
            </div>        
        </form>
    </div>                             
</div>
{% endlanguage %}

<script>
   
    var form_options = {
        target: '#form-modal-body-body',
    }
    $('#loginform').ajaxForm(form_options);
    
</script>

surogaAPI/templates/partner/clientsignup.html
{% load i18n widget_tweaks %}

{% language  code  %}
<p class="modal-title text-center">{% trans "Sign UP for ride" %}</p>
                                      
<form id="client_signup" method="post" class="form-horizontal" action="{% url 'partner:client_signup' %}"> 
{% csrf_token %}
{% for field in form %}
    <div class="form-group">
    {{ field }}
    {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
    {% endfor %}
    </div>
{% endfor %}

<input type="submit" value = "{% trans 'Sign up' %}" class="btn btn-green btn-block">
</form>

{% endlanguage %}

<script>
    
var form_options = {
    target: '#form-modalSignup-body',
}


$('#client_signup').ajaxForm(form_options);
</script>

surogaAPI/templates/partner/confirm.html
<script>
    $('#generic-modal').modal('hide'); 
    $('body').on('hidden.bs.modal', '.modal', function () {
        $(this).removeData('bs.modal');
    });
    window.location = ".";
</script>

surogaAPI/templates/partner/confirmLogin.html
<script>
    $('#form-modal').modal('hide'); 
    $('body').on('hidden.bs.modal', '.modal', function () {
        $(this).removeData('bs.modal');
    });
    window.location = ".";
</script>

surogaAPI/templates/partner/confirmSignup.html
<script>
    $('#form-modalSignup').modal('hide'); 
    $('body').on('hidden.bs.modal', '.modal', function () {
        $(this).removeData('bs.modal');
    });
    window.location = ".";
</script>

surogaAPI/templates/partner/menu.html
{% load static %}
{% load i18n %}

{% get_available_languages as languages %}
{% get_current_language as LANGUAGE_CODE %}
{% get_language_info for LANGUAGE_CODE as lang %}

<div class="navbar navbar-inverse navbar-fixed-top scrollclass" >
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand one" href="#"><img src="{% static 'img/head_logo.png'%}" alt="" class="user-img img-logo image-responsive" /></a>

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'partner:client_dashboard' %}">HOME</a></li>
                <li><a href="{% url 'partner:profile-update' partner.pk %}">PROFILE</a></li>
                <li class="dropdown">
                    <a id="select-lang" href="#" class="dropdown-toggle text-light" data-toggle="dropdown" role="button" aria-expanded="false" style="text-transform: capitalize;"> {{ lang.name_local }} <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            {% for lang_code, lang_name in languages %}
                                {% language lang_code %}
                                <li><a  href="#" onclick="setlang('{{ lang_code }}')">{{ lang_name }}</a></li>
                                
                                {% endlanguage %}
                            {% endfor %}
                        </ul>
                </li>
                <li> <a id="Login-button" class="btn btn-outline-primary my-2 my-sm-0" type="button">{% trans "LOG OUT" %}</a></li>
            </ul>
        </div>
       
    </div>
</div>
	
  <div id="generic-modal" class="modal" tabindex="-1" role="dialog" aria-hidden="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content" >
                <div class="modal-header">
                    <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="text-right">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                    </div>
                </div>
                                        
                <div id="generic-modal-body" class="modal-body">
                    <div class="container-fluid">
  

                            <div id="generic-modal-body-body">
                                <p>One fine body&hellip;</p>
                            </div>
                            
                            <p style="padding-bottom: 0.2cm;"></p>
                    </div>
                </div>
             </div>
    </div>
  </div> 
{% block extra_js %}
<!-- script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js" integrity="sha512-YUkaLm+KJ5lQXDBdqBqk7EVhJAdxRnVdT2vtCzwPHSweCzyMgYV/tgGF4/dCyqtCC2eCphz0lRQgatGVdfR0ww==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.1/js/bootstrap.min.js" integrity="sha512-vyRAVI0IEm6LI/fVSv/Wq/d0KUfrg3hJq2Qz5FlfER69sf3ZHlOrsLriNm49FxnpUGmhx+TaJKwJ+ByTLKT+Yg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script !-->

<!-- script src="https://code.jquery.com/jquery-2.1.3.min.js"></script -->
<script src="{% static 'js/popper.min.js'%}"></script>
<script src="{% static 'js/jquery.min.js'%}"></script>

<script src="{% static 'js/jquery.form.min.js'%}"></script>
<script src="{% static 'js/tether.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<script src="{% static 'js/jquery.easing.min.js'%}"></script>
<script src="{% static 'js/owl.carousel.min.js'%}"></script>
<script src="{% static 'js/wow.min.js'%}"></script>   
<script >


function setlang(code) {
    $.ajax({                       
            url: '/ajax/setlang/', 
            data: {
            'lang_code': code,
            },
            success: function (data) { 
                setTimeout(function(){
                    window.location = ".";
                },100);
            }
        })
}

$('#Login-button').click(function(event) {
        $.ajax({                       
            url: '/partner/logout/', 
            success: function (data) {   
                window.location='/';
            }
        })
});

</script>

{% endblock extra_js %}

surogaAPI/templates/partner/searchLogin.html
{% load static %}
{% load i18n %}

{% get_available_languages as languages %}
{% get_current_language as LANGUAGE_CODE %}
{% get_language_info for LANGUAGE_CODE as lang %}

<table id="tableLogin" style="width:100%">
    <thead>
        <tr>
            <th>Date</th>
            <th>IP</th>
            <th>Local</th>
            <th>country</th>
          </tr>
    </thead>
    
    <tbody>
        {% for data, ip, local, country in AccessLog%}
        <tr>
            <td>{{ data }}</td>
            <td>{{ ip }}</td>
            <td>{{ local }}</td>
            <td>{{ country }}</td>

        </tr>
        {% empty %}
        <tr>
            <td>{% trans "Empty" %}</td>
         </tr>
        {% endfor %}
    </tbody>
    
</table>

surogaAPI/templates/partner/searchRequests.html
{% load static %}
{% load i18n %}

{% get_available_languages as languages %}
{% get_current_language as LANGUAGE_CODE %}
{% get_language_info for LANGUAGE_CODE as lang %}

<table id="tableRequests" style="width:100%">
    <thead>
        <tr>
            <th>Date</th>
            <th>Type</th>
            <th>Request</th>
            <th>IP</th>
            <th></th>
          </tr>
    </thead>
    <tbody>
        {% for pk, data, type, request, ip in EventLog %}
        <tr>
            <td>{{ data }}</td>
            <td>{{ type }}</td>
            <td>{{ request }}</td>
            <td>{{ ip }}</td>
            <td>
                <button onclick="viewRequest( '{{ pk }}')"  class="col btn btn-green text-litle custom-buton text-center">{% trans "View" %}</button> 
            </td>
        </tr>
        {% empty %}
        <tr>
            <td>{% trans "Empty" %}</td>
         </tr>
        {% endfor %}
    </tbody>
</table>

surogaAPI/templates/partner/updatelocal.html
{% load i18n widget_tweaks %}

{% language  code  %}
<p class="modal-title text-center">{% trans "contactUpdate App covered local" %}</p>
<p style="padding-bottom: .5cm;"></p>                    
                          
<form id="contact" method="post" class="form-horizontal" action="{% url 'partner:local-update' pk %}"> 
{% csrf_token %}
<div class="form-group row">
    <label for="Country" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "Country"  %}:</label>
    <div class="col-sm-9">
    {{ form.Country }}
    </div>
    <p style="color: red">{{ form.Country.errors }} </p> 
</div>

<div class="form-group row">
    <label for="DistrictRegion" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "Distric/tRegion"  %}:</label>
    <div class="col-sm-9">
    {{ form.DistrictRegion }} 
    </div>
    <p style="color: red">{{ form.DistrictRegion.errors }} </p> 
</div>

<div class="form-group row">
    <label for="CityMunicipality" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "City/Municipality"  %}:</label>
    <div class="col-sm-9">
    {{ form.CityMunicipality }}
    </div>
    <p style="color: red">{{ form.CityMunicipality.errors }} </p> 
</div>

<div class="form-group row">
    <label for="ServiceCategory" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "Service category"  %}:</label>
    <div class="col-sm-9">
    {{ form.ServiceCategory }}
    </div>
    <p style="color: red">{{ form.ServiceCategory.errors }} </p> 
</div>

<input type="submit" value = "{% trans 'Save' %}" class="btn btn-green btn-block">
</form>
<p style="padding-bottom: .5cm;"></p>
{% endlanguage %}

<script>
    
var form_options = {
    target: '#generic-modal-body-body',
}


$('#contact').ajaxForm(form_options);
</script>

surogaAPI/templates/partner/viewLogin.html
{% load static %}
{% load i18n %}

{% get_available_languages as languages %}
{% get_current_language as LANGUAGE_CODE %}
{% get_language_info for LANGUAGE_CODE as lang %}

<div class="container">
    <div class="form-group row">
        <label for="Registration" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "Operation Type"  %}:</label>
        <div class="col-sm-9">
        <input name="Registration" type="text" value="{{ item.RegistrationDate }}"  readonly> 
        </div>
    </div>
    <div class="form-group row">
        <label for="IP" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "IP"  %}:</label>
        <div class="col-sm-9">
        <input name="IP" type="text" value="{{ item.IP }}" readonly> 
        </div>
    </div>
    <div class="form-group row">
        <label for="local" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "Local"  %}:</label>
        <div class="col-sm-9">
        <input name="local" type="text" value="{{ item.local }}"  readonly> 
        </div>
    </div>
    <div class="form-group row">
        <label for="country" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "Country"  %}:</label>
        <div class="col-sm-9">
        <input name="country" type="text" value="{{ item.country }}"  readonly> 
        </div>
    </div>
</div>

surogaAPI/templates/partner/viewRequest.html
{% load static %}
{% load i18n %}

{% get_available_languages as languages %}
{% get_current_language as LANGUAGE_CODE %}
{% get_language_info for LANGUAGE_CODE as lang %}

<div class="container">
    <div class="form-group row">
        <label for="Registration" class="col-sm-2 col-form-label" style="text-align: right;">{% trans "Date"  %}:</label>
        <div class="col-sm-10">
        <input name="Registration" type="text" value="{{ item.added_on }}"  readonly> 
        </div>
    </div>
    <div class="form-group row">
        <label for="Type" class="col-sm-2 col-form-label" style="text-align: right;">{% trans "Event Type"  %}:</label>
        <div class="col-sm-10">
        <input name="Type" type="text" value="{{ item.method }}" readonly> 
        </div>
    </div>
    <div class="form-group row">
        <label for="api" class="col-sm-2 col-form-label" style="text-align: right;">{% trans "API"  %}:</label>
        <div class="col-sm-10">
        <input name="api" style="size-adjust: 100%;" type="text" value="{{ item.api }}" readonly> 
        </div>
    </div>
   
    <div class="form-group row">
        <label for="headers" class="col-sm-2 col-form-label" style="text-align: right;">{% trans "Headers"  %}:</label>
        <div class="col-sm-10">
            <textarea name="headers" readonly>
                {{ item.headers }}
            </textarea> 
        </div>
    </div>

    <div class="form-group row">
        <label for="body" class="col-sm-2 col-form-label" style="text-align: right;">{% trans "Body"  %}:</label>
        <div class="col-sm-10">
            <textarea name="body" readonly>
                {{ item.body }}
            </textarea> 
        </div>
    </div>

    <div class="form-group row">
        <label for="client_ip_address" class="col-sm-2 col-form-label" style="text-align: right;">{% trans "IP address"  %}:</label>
        <div class="col-sm-10">
        <input name="client_ip_address" type="text" value="{{ item.client_ip_address }}"  readonly> 
        </div>
    </div>

    <div class="form-group row">
        <label for="Response" class="col-sm-2 col-form-label" style="text-align: right;">{% trans "Response"  %}:</label>
        <div class="col-sm-10">
            <textarea name="Response" readonly>
                {{ item.response }}
            </textarea> 
        </div>
    </div>

    <div class="form-group row">
        <label for="status_code" class="col-sm-2 col-form-label" style="text-align: right;">{% trans "Status code"  %}:</label>
        <div class="col-sm-10">
        <input name="status_code" type="text" value="{{ item.status_code }}"  readonly> 
        </div>
    </div>
    <div class="form-group row">
        <label for="execution_time" class="col-sm-2 col-form-label" style="text-align: right;">{% trans "Execution time"  %}:</label>
        <div class="col-sm-10">
        <input name="execution_time" type="text" value="{{ item.execution_time }}"  readonly> 
        </div>
    </div>
</div>

surogaAPI/templates/partner/viewTransation.html
{% load static %}
{% load i18n %}

{% get_available_languages as languages %}
{% get_current_language as LANGUAGE_CODE %}
{% get_language_info for LANGUAGE_CODE as lang %}

<div class="container">
    <div class="form-group row">
        <label for="Registration" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "Date"  %}:</label>
        <div class="col-sm-9">
        <input name="Registration" type="text" value="{{ item.RegistrationDate }}"  readonly> 
        </div>
    </div>
    <div class="form-group row">
        <label for="OperationType" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "Operation Type"  %}:</label>
        <div class="col-sm-9">
        <input name="OperationType" type="text" value="{{ item.OperationType }}"  readonly> 
        </div>
    </div>
    <div class="form-group row">
        <label for="SettlementDate" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "Settlement Date"  %}:</label>
        <div class="col-sm-9">
        <input name="SettlementDate" type="text" value="{{ item.OperationType }}" readonly> 
        </div>
    </div>
    <div class="form-group row">
        <label for="PaymMethodResul" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "PaymMethod Resul"  %}:</label>
        <div class="col-sm-9">
        <input name="PaymMethodResul" type="text" value="{{ item.PaymMethodResul }}"  readonly> 
        </div>
    </div>
    <div class="form-group row">
        <label for="StripTransactionID" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "Strip Transaction ID"  %}:</label>
        <div class="col-sm-9">
        <input name="StripTransactionID" type="text" value="{{ item.StripTransactionID }}"  readonly> 
        </div>
    </div>
    <div class="form-group row">
        <label for="SurooBankTransactionID" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "Suroo Bank Transaction ID"  %}:</label>
        <div class="col-sm-9">
        <input name="SurooBankTransactionID" type="text" value="{{ item.SurooBankTransactionID }}"  readonly> 
        </div>
    </div>
    <div class="form-group row">
        <label for="Ride" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "Ride"  %}:</label>
        <div class="col-sm-9">
        <input name="Ride" type="text" value="{{ item.Ride.pk }}"  readonly> 
        </div>
    </div>
    <div class="form-group row">
        <label for="Booking" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "Booking"  %}:</label>
        <div class="col-sm-9">
        <input name="Booking" type="text" value="{{ item.Ride.pk }}"  readonly> 
        </div>
    </div>
    <div class="form-group row">
        <label for="Value" class="col-sm-3 col-form-label" style="text-align: right;">{% trans "Value"  %}:</label>
        <div class="col-sm-9">
        <input name="Value" type="number" value="{{ item.Value}}" readonly> 
        </div>
    </div>

</div>